# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: sujilee <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/11/29 13:14:07 by sujilee           #+#    #+#              #
#    Updated: 2021/11/29 14:48:35 by sujilee          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME := libft.a

SRCS := first.c second.c third.c

OBJS := first.o second.o third.o

AR := ar

ARFLAGS := -rcs

$(NAME) : $(OBJS)
	    $(AR) $(ARFLAGS) $@ $?		   
